# Generated by Django 5.0.3 on 2024-04-09 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("TestingSystem", "0001_initial"),
        ("UserResponse", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="testquestionrandomizemodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_random",
                to="UserResponse.userregistermodel",
            ),
        ),
        migrations.AddField(
            model_name="truefalsemodel",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="truefalse",
                to="TestingSystem.questionmodel",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="testquestionrandomizemodel",
            index=models.Index(
                fields=["user", "test", "order"], name="TestingSyst_user_id_710314_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testquestionrandomizemodel",
            unique_together={("user", "test", "question")},
        ),
    ]
