# Generated by Django 5.0.3 on 2024-04-09 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("UserResponse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserResponseScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField()),
                ("ranks", models.PositiveIntegerField()),
                ("persentage", models.FloatField()),
                ("is_passed", models.BooleanField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_score",
                        to="UserResponse.userregistermodel",
                    ),
                ),
            ],
        ),
    ]
