# Generated by Django 5.0.3 on 2024-04-09 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("AssignLinks", "0001_initial"),
        ("TestingSystem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignlinkmodel",
            name="test_MTO",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assign_link_test",
                to="TestingSystem.testmodel",
            ),
        ),
        migrations.AddField(
            model_name="assignlinkmodel",
            name="attempts_OTO",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assign_link_attempts",
                to="AssignLinks.attemptsmodel",
            ),
        ),
        migrations.AddField(
            model_name="assignlinkmodel",
            name="availability_OTO",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assign_link_availability",
                to="AssignLinks.availabilitymodel",
            ),
        ),
        migrations.AddField(
            model_name="assignlinkmodel",
            name="display_each_question_OTO",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assign_link_display_each_question",
                to="AssignLinks.displayeachquestionmodel",
            ),
        ),
        migrations.AddField(
            model_name="assignlinkmodel",
            name="email_results_instructor_OTO",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assign_link_email_results_instructor",
                to="AssignLinks.emailresultsinstructormodel",
            ),
        ),
        migrations.AddField(
            model_name="assignlinkmodel",
            name="instruction_OTO",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instruction",
                to="AssignLinks.instructionmodel",
            ),
        ),
        migrations.AddField(
            model_name="assignlinkmodel",
            name="limit_time_OTO",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assign_link_limit_time",
                to="AssignLinks.limittimemodel",
            ),
        ),
        migrations.AddField(
            model_name="assignlinkmodel",
            name="pass_mark_and_feedback_OTO",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assign_link_pass_mark_and_feedback",
                to="AssignLinks.passmarkandfeedbackmodel",
            ),
        ),
        migrations.AddField(
            model_name="assignlinkmodel",
            name="print_copy_paste_translate_OTO",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assign_link_print_copy_paste_translate",
                to="AssignLinks.print_copy_paste_translatemodel",
            ),
        ),
        migrations.AddField(
            model_name="assignlinkmodel",
            name="restrictions_OTO",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assign_link_restrictions",
                to="AssignLinks.restrictionsmodel",
            ),
        ),
        migrations.AddField(
            model_name="assignlinkmodel",
            name="results_page_OTO",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results_page",
                to="AssignLinks.resultspagemodel",
            ),
        ),
        migrations.AddField(
            model_name="assignlinkmodel",
            name="taker_email_send_OTO",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assign_link_taker_email_send",
                to="AssignLinks.takeremailsendmodel",
            ),
        ),
    ]
